//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuAn
    {
        public int IDduan { get; set; }
        public string Tenduan { get; set; }
        public Nullable<int> IDnhadautu { get; set; }
        public Nullable<int> IDlichtrinh { get; set; }
        public Nullable<int> kinhphi { get; set; }
        public Nullable<int> IDkhachhang { get; set; }
        public Nullable<int> IDnhanvien { get; set; }
        public Nullable<int> IDhopdong { get; set; }
    
        public virtual Hopdong Hopdong { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Lichtrinh Lichtrinh { get; set; }
        public virtual Nhadautu Nhadautu { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
    }
}
