//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taikhoan
    {
        public string TenTk { get; set; }
        public string Matkhau { get; set; }
        public string Sđt { get; set; }
    }
}
