//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thongbao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thongbao()
        {
            this.Lichtrinhs = new HashSet<Lichtrinh>();
        }
    
        public int IDthongbao { get; set; }
        public string Tenthongbao { get; set; }
        public Nullable<System.DateTime> Ngaythongbao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lichtrinh> Lichtrinhs { get; set; }
    }
}
